// ICPC-2 Code structure
export interface ICPC2Code {
  code: string;
  description: string;
}

// MGF ICPC-2 Codes - Complete list
export const MGF_ICPC2_CODES: ICPC2Code[] = [
  // A - General and Unspecified
  { code: "A01", description: "Dor generalizada / múltipla" },
  { code: "A02", description: "Arrepios" },
  { code: "A03", description: "Febre" },
  { code: "A04", description: "Debilidade / cansaço geral" },
  { code: "A05", description: "Sentir-se doente" },
  { code: "A06", description: "Desmaio / síncope" },
  { code: "A07", description: "Coma" },
  { code: "A08", description: "Inchaço" },
  { code: "A09", description: "Problemas de sudorese" },
  { code: "A10", description: "Sangramento / hemorragia NE" },
  { code: "A11", description: "Dores torácicas NE" },
  { code: "A13", description: "Receio ou medo do tratamento" },
  { code: "A16", description: "Criança irritável" },
  { code: "A18", description: "Preocupação com a aparência" },
  { code: "A20", description: "Pedido / discussão da eutanásia" },
  { code: "A21", description: "Factor de risco de malignidade" },
  { code: "A23", description: "Factor de risco NE" },
  { code: "A25", description: "Medo de morrer / da morte" },
  { code: "A26", description: "Medo de cancro NE" },
  { code: "A27", description: "Medo de outra doença NE" },
  { code: "A28", description: "Limitação funcional / incapacidade NE" },
  { code: "A29", description: "Outros sinais / sintomas gerais" },
  { code: "A70", description: "Tuberculose" },
  { code: "A71", description: "Sarampo" },
  { code: "A72", description: "Varicela" },
  { code: "A73", description: "Malária" },
  { code: "A74", description: "Rubéola" },
  { code: "A75", description: "Mononucleose infecciosa" },
  { code: "A76", description: "Outro exantema viral" },
  { code: "A77", description: "Outras doenças virais NE" },
  { code: "A78", description: "Outras doenças infecciosas NE" },
  {
    code: "A79",
    description: "Carcinomatose (localização primária desconhecida) NE",
  },
  { code: "A80", description: "Lesão traumática / acidente NE" },
  { code: "A81", description: "Politraumatismos / ferimentos múltiplos" },
  { code: "A82", description: "Efeito secundário de uma lesão traumática" },
  { code: "A84", description: "Intoxicação por medicamento" },
  { code: "A85", description: "Efeitos secundários de um fármaco" },
  { code: "A86", description: "Efeito tóxico de uma substância não-medicinal" },
  { code: "A87", description: "Complicações do tratamento" },
  { code: "A88", description: "Efeitos secundários por factores físicos" },
  { code: "A89", description: "Efeitos de uma prótese" },
  { code: "A90", description: "Malformações congénitas NE / múltiplas" },
  { code: "A91", description: "Investigação com resultados anormais NE" },
  { code: "A92", description: "Alergia / reacção alérgica NE" },
  { code: "A93", description: "Recém-nascido prematuro" },
  { code: "A94", description: "Morbilidade perinatal, outra" },
  { code: "A95", description: "Mortalidade perinatal" },
  { code: "A96", description: "Morte" },
  { code: "A97", description: "Sem doença" },
  { code: "A98", description: "Medicina preventiva / manutenção da saùde" },
  {
    code: "A99",
    description:
      "Doença ou condição de natureza ou localização não especificadas",
  },

  // B - Blood, Blood Forming Organs and Immune Mechanism
  {
    code: "B02",
    description: "Gânglio(s) linfático(s) aumentado(s) de volume/doloroso(s)",
  },
  { code: "B04", description: "Sinais/sintomas do sangue" },
  { code: "B25", description: "Medo de SIDA/VIH" },
  { code: "B26", description: "Medo de cancro do sangue/linfático" },
  { code: "B27", description: "Medo de outras doenças do sangue/linfáticos" },
  { code: "B28", description: "Limitação funcional/incapacidade" },
  {
    code: "B29",
    description: "Outros sinais/sintomas do sangue/linfático/baço NE",
  },
  { code: "B70", description: "Linfadenite aguda" },
  { code: "B71", description: "Linfadenite crónica / não específica" },
  { code: "B72", description: "Doença de Hodgkin/linfomas" },
  { code: "B73", description: "Leucemia" },
  { code: "B74", description: "Outra neoplasia maligna do sangue" },
  { code: "B75", description: "Neoplasias benignas NE" },
  { code: "B76", description: "Rotura do baço" },
  {
    code: "B77",
    description: "Outras lesões traumáticas do sangue/linfa/baço",
  },
  { code: "B78", description: "Anemias hemolíticas hereditárias" },
  {
    code: "B79",
    description: "Outra malformação congénita do sangue/linfática",
  },
  { code: "B80", description: "Anemia por deficiência de ferro" },
  {
    code: "B81",
    description: "Anemia por deficiência de vitamina B12 / folatos",
  },
  { code: "B82", description: "Outras anemias não especificadas" },
  { code: "B83", description: "Púrpura/defeitos de coagulação" },
  { code: "B84", description: "Glóbulos brancos anormais inexplicados" },
  { code: "B87", description: "Esplenomegália" },
  { code: "B90", description: "Infecção-VIH, SIDA" },
  { code: "B99", description: "Outra doença do sangue / linfáticos / baço" },

  // D - Digestive
  { code: "D01", description: "Dor / cólica abdominal generalizada" },
  { code: "D02", description: "Dor abdominal epigástrica" },
  { code: "D03", description: "Azia" },
  { code: "D04", description: "Dor anal / rectal" },
  { code: "D05", description: "Irritação perianal" },
  { code: "D06", description: "Dor abdominal localizada, outra" },
  { code: "D07", description: "Dispepsia / indigestão" },
  { code: "D08", description: "Flatulência / meteorismo / eructação" },
  { code: "D09", description: "Náusea" },
  { code: "D10", description: "Vómitos" },
  { code: "D11", description: "Diarreia" },
  { code: "D12", description: "Obstipação" },
  { code: "D13", description: "Icterícia" },
  { code: "D14", description: "Hematemese / vómito de sangue" },
  { code: "D15", description: "Melena" },
  { code: "D16", description: "Hemorragia rectal" },
  { code: "D17", description: "Incontinência intestinal" },
  { code: "D18", description: "Alteração nas fezes / movimentos intestinais" },
  { code: "D19", description: "Sinal / sintoma dos dentes / gengivas" },
  { code: "D20", description: "Sinal / sintoma da boca / língua / lábios" },
  { code: "D21", description: "Problema de deglutição" },
  { code: "D23", description: "Hepatomegália" },
  { code: "D24", description: "Massa abdominal ne" },
  { code: "D25", description: "Distensão abdominal" },
  { code: "D26", description: "Medo de cancro do aparelho digestivo" },
  { code: "D27", description: "Medo de outra doença do aparelho digestivo" },
  { code: "D28", description: "Limitação funcional / incapacidade (d)" },
  { code: "D29", description: "Sinal / sintoma digestivo, outro" },
  { code: "D70", description: "Infecção gastrointestinal" },
  { code: "D71", description: "Papeira / parotidite epidémica" },
  { code: "D72", description: "Hepatite viral" },
  { code: "D73", description: "Gastroenterite, presumível infecção" },
  { code: "D74", description: "Neoplasia maligna do estômago" },
  { code: "D75", description: "Neoplasia maligna do cólon / recto" },
  { code: "D76", description: "Neoplasia maligna do pâncreas" },
  {
    code: "D77",
    description: "Neoplasia maligna do aparelho digestivo, outra / ne",
  },
  {
    code: "D78",
    description: "Neoplasia do aparelho digestivo benigna / incerta",
  },
  { code: "D79", description: "Corpo estranho no aparelho digestivo" },
  { code: "D80", description: "Lesão traumática, outra" },
  { code: "D81", description: "Malformação congénita do aparelho digestivo" },
  { code: "D82", description: "Doença dos dentes / gengivas" },
  { code: "D83", description: "Doença da boca / lingua / lábios" },
  { code: "D84", description: "Doença do esófago" },
  { code: "D85", description: "Úlcera do duodeno" },
  { code: "D86", description: "Úlcera péptica, outra" },
  { code: "D87", description: "Alteração funcional do estômago" },
  { code: "D88", description: "Apendicite" },
  { code: "D89", description: "Hérnia inguinal" },
  { code: "D90", description: "Hérnia de hiato" },
  { code: "D91", description: "Hérnia abdominal, outra" },
  { code: "D92", description: "Doença diverticular intestinal" },
  { code: "D93", description: "Síndrome do cólon irritável" },
  { code: "D94", description: "Enterite crónica / colite ulcerosa" },
  { code: "D95", description: "Fissura anal / abcesso perianal" },
  { code: "D96", description: "Lombrigas / outros parasitas" },
  { code: "D97", description: "Doença de fígado, outra" },
  { code: "D98", description: "Colecistite, colelitíase" },
  { code: "D99", description: "Doença do sistema digestivo, outra" },

  // F - Eye
  { code: "F01", description: "Dor no olho" },
  { code: "F02", description: "Olho vermelho" },
  { code: "F03", description: "Secreção ocular" },
  { code: "F04", description: "Moscas volantes / pontos luminosos / manchas" },
  { code: "F05", description: "Perturbação visual, outra" },
  { code: "F13", description: "Sensação ocular anormal" },
  { code: "F14", description: "Movimentos oculares anormais" },
  { code: "F15", description: "Aparência anormal do olho" },
  { code: "F16", description: "Sinal / sintoma da pálpebra" },
  { code: "F17", description: "Sinal / sintoma relacionado com os óculos" },
  {
    code: "F18",
    description: "Sinal / sintoma relacionado com as lentes de contacto",
  },
  { code: "F27", description: "Medo de doença ocular" },
  { code: "F28", description: "Limitação funcional / incapacidade (f)" },
  { code: "F29", description: "Sinal / sintoma ocular, outro" },
  { code: "F70", description: "Conjuntivite infecciosa" },
  { code: "F71", description: "Conjuntivite alérgica" },
  { code: "F72", description: "Blefarite / hordeólo / calázio" },
  { code: "F73", description: "Infecção / inflamação ocular, outra" },
  { code: "F74", description: "Neoplasia do olho / anexos" },
  { code: "F75", description: "Contusão / hemorragia ocular" },
  { code: "F76", description: "Corpo estranho ocular" },
  { code: "F79", description: "Lesão traumática ocular, outra" },
  { code: "F80", description: "Obstrução do canal lacrimal da criança" },
  { code: "F81", description: "Malformação congénita do olho, outra" },
  { code: "F82", description: "Descolamento da retina" },
  { code: "F83", description: "Retinopatia" },
  { code: "F84", description: "Degenerescência macular" },
  { code: "F85", description: "Úlcera da córnea" },
  { code: "F86", description: "Tracoma" },
  { code: "F91", description: "Erro de refracção" },
  { code: "F92", description: "Catarata" },
  { code: "F93", description: "Glaucoma" },
  { code: "F94", description: "Cegueira" },
  { code: "F95", description: "Estrabismo" },
  { code: "F99", description: "Doença ocular / anexos, outra" },

  // H - Ear
  { code: "H01", description: "Dor de ouvidos" },
  { code: "H02", description: "Problema de audição" },
  { code: "H03", description: "Acufeno / zumbido, ruído, assobio" },
  { code: "H04", description: "Secreção do ouvido" },
  { code: "H05", description: "Hemorragia do ouvido" },
  { code: "H13", description: "Sensação de ouvido tapado" },
  { code: "H15", description: "Preocupação com a aparência das orelhas" },
  { code: "H27", description: "Medo de doença do ouvido" },
  { code: "H28", description: "Limitação funcional / incapacidade (h)" },
  { code: "H29", description: "Sinal / sintoma do ouvido, outro" },
  { code: "H70", description: "Otite externa" },
  { code: "H71", description: "Otite média aguda / miringite" },
  { code: "H72", description: "Otite média serosa" },
  { code: "H73", description: "Infecção da trompa de eustáquio" },
  { code: "H74", description: "Otite média crónica" },
  { code: "H75", description: "Neoplasia do ouvido" },
  { code: "H76", description: "Corpo estranho no ouvido" },
  { code: "H77", description: "Perfuraçâo do tímpano" },
  { code: "H78", description: "Traumatismo superficial do ouvido" },
  { code: "H79", description: "Traumatismo do ouvido, outro" },
  { code: "H80", description: "Malformação congénita do ouvido" },
  { code: "H81", description: "Cerumen no ouvido em excesso" },
  { code: "H82", description: "Síndrome vertiginoso" },
  { code: "H83", description: "Otoesclerose" },
  { code: "H84", description: "Presbiacusia" },
  { code: "H85", description: "Lesão acústica" },
  { code: "H86", description: "Surdez" },
  { code: "H99", description: "Doença do ouvido / mastóide, outra" },

  // K - Cardiovascular
  { code: "K01", description: "Dor atribuída ao coração" },
  {
    code: "K02",
    description: "Sensação de pressão / aperto atribuído ao coração",
  },
  { code: "K03", description: "Dor atribuída ao aparelho circulatório, outra" },
  { code: "K04", description: "Palpitações / percepção do batimento cardíaco" },
  { code: "K05", description: "Irregularidade do batimento cardíaco, outra" },
  { code: "K06", description: "Veias proeminentes" },
  { code: "K07", description: "Tornozelos inchados / edema" },
  { code: "K22", description: "Factor de risco de doença cardiovascular" },
  { code: "K24", description: "Medo de doença cardíaca" },
  { code: "K25", description: "Medo de hipertensão" },
  { code: "K27", description: "Medo de outra doença cardiovascular" },
  { code: "K28", description: "Limitação funcional / incapacidade (k)" },
  { code: "K29", description: "Sinal / sintoma cardiovascular, outro" },
  { code: "K70", description: "Doença infecciosa do aparelho circulatório" },
  { code: "K71", description: "Febre reumática / cardiopatia" },
  { code: "K72", description: "Neoplasia do aparelho circulatório" },
  {
    code: "K73",
    description: "Malformação congénita do aparelho circulatório",
  },
  { code: "K74", description: "Doença cardíaca isquémica com angina" },
  { code: "K75", description: "Enfarte agudo do miocárdio" },
  { code: "K76", description: "Doença cardíaca isquémica sem angina" },
  { code: "K77", description: "Insuficiência cardíaca" },
  { code: "K78", description: "Fibrilhação / flutter auricular" },
  { code: "K79", description: "Taquicardia paroxística" },
  { code: "K80", description: "Arritmia cardíaca ne" },
  { code: "K81", description: "Sopro cardíaco / arterial ne" },
  { code: "K82", description: "Doença cardio-pulmonar" },
  { code: "K83", description: "Doença valvular cardíaca ne" },
  { code: "K84", description: "Doença cardíaca, outra" },
  { code: "K85", description: "Tensão arterial elevada" },
  { code: "K86", description: "Hipertensão sem complicações" },
  { code: "K87", description: "Hipertensão com complicações" },
  { code: "K88", description: "Hipotensão postural" },
  { code: "K89", description: "Isquémia cerebral transitória" },
  { code: "K90", description: "Trombose / acidente vascular cerebral" },
  { code: "K91", description: "Doença vascular cerebral" },
  { code: "K92", description: "Aterosclerose / doença vascular periférica" },
  { code: "K93", description: "Embolia pulmonar" },
  { code: "K94", description: "Flebite e tromboflebite" },
  { code: "K95", description: "Veias varicosas da perna" },
  { code: "K96", description: "Hemorróidas" },
  { code: "K99", description: "Doença do aparelho circulatório, outra" },

  // L - Musculoskeletal
  { code: "L01", description: "Sinal / sintoma do pescoço" },
  { code: "L02", description: "Sinal / sintoma da região dorsal" },
  { code: "L03", description: "Sinal / sintoma da região lombar" },
  { code: "L04", description: "Sinal / sintoma do tórax" },
  { code: "L05", description: "Sinal / sintoma do flanco / axila" },
  { code: "L07", description: "Sinal / sintoma da mandíbula" },
  { code: "L08", description: "Sinal / sintoma do ombro" },
  { code: "L09", description: "Sinal / sintoma do braço" },
  { code: "L10", description: "Sinal / sintoma do cotovelo" },
  { code: "L11", description: "Sinal / sintoma do punho" },
  { code: "L12", description: "Sinal / sintoma da mão / dedo" },
  { code: "L13", description: "Sinal / sintoma da anca" },
  { code: "L14", description: "Sinal / sintoma da perna / coxa" },
  { code: "L15", description: "Sinal / sintoma do joelho" },
  { code: "L16", description: "Sinal / sintoma do tornozelo" },
  { code: "L17", description: "Sinal / sintoma do pé / dedo do pé" },
  { code: "L18", description: "Dor muscular" },
  { code: "L19", description: "Sinal / sintoma muscular ne" },
  { code: "L20", description: "Sinal / sintoma de articulação ne" },
  {
    code: "L26",
    description: "Medo de cancro do aparelho músculo-esquelético",
  },
  {
    code: "L27",
    description: "Medo de doença do aparelho músculo-esquelético, outra",
  },
  { code: "L28", description: "Limitação funcional / incapacidade (l)" },
  {
    code: "L29",
    description: "Sinal / sintoma do aparelho músculo-esquelético, outro",
  },
  { code: "L70", description: "Infecção do aparelho músculo-esquelético" },
  { code: "L71", description: "Neoplasia maligna" },
  { code: "L72", description: "Fractura: rádio / cúbito" },
  { code: "L73", description: "Fractura: tíbia / peróneo" },
  { code: "L74", description: "Fractura: osso da mão / pé" },
  { code: "L75", description: "Fractura: fémur" },
  { code: "L76", description: "Fractura, outras" },
  { code: "L77", description: "Entorse / distensão do tornozelo" },
  { code: "L78", description: "Entorse / distensão do joelho" },
  { code: "L79", description: "Entorse / distensão de articulação ne" },
  { code: "L80", description: "Luxação / subluxação" },
  {
    code: "L81",
    description: "Traumatismo do aparelho músculo-esquelético ne",
  },
  { code: "L82", description: "Malformação congénita músculo-esqueléticas" },
  { code: "L83", description: "Síndrome da coluna cervical" },
  { code: "L84", description: "Síndrome da coluna sem irradiação de dor" },
  { code: "L85", description: "Deformação adquirida da coluna" },
  { code: "L86", description: "Síndrome da coluna com irradiação de dores" },
  { code: "L87", description: "Bursite / tendinite / sinovite ne" },
  { code: "L88", description: "Artrite reumatóide / seropositiva" },
  { code: "L89", description: "Osteoartrose da anca" },
  { code: "L90", description: "Osteoartrose do joelho" },
  { code: "L91", description: "Osteoartrose, outra" },
  { code: "L92", description: "Síndrome do ombro doloroso" },
  { code: "L93", description: "Cotovelo de tenista" },
  { code: "L94", description: "Osteocondrose" },
  { code: "L95", description: "Osteoporose" },
  { code: "L96", description: "Lesão interna aguda do joelho" },
  {
    code: "L97",
    description: "Neoplasia benignas / incerta do aparelho músculo-esquelético",
  },
  { code: "L98", description: "Malformação adquirida de um membro" },
  { code: "L99", description: "Doença do aparelho músculo-esquelético, outra" },

  // N - Neurological
  { code: "N01", description: "Cefaleia" },
  { code: "N03", description: "Dor da face" },
  { code: "N04", description: "Síndrome das pernas inquietas" },
  { code: "N05", description: "Formigueiro nos dedos / mãos / pés" },
  { code: "N06", description: "Alteração da sensibilidade, outra" },
  { code: "N07", description: "Convulsões / ataques" },
  { code: "N08", description: "Movimentos involuntários anormais" },
  { code: "N16", description: "Alteração do olfacto / gosto" },
  { code: "N17", description: "Vertigens / tonturas" },
  { code: "N18", description: "Paralisia / fraqueza" },
  { code: "N19", description: "Perturbação da fala" },
  { code: "N26", description: "Medo de cancro do sistema neurológico" },
  { code: "N27", description: "Medo de outra doença neurológica" },
  { code: "N28", description: "Limitação funcional / incapacidade (n)" },
  { code: "N29", description: "Sinal / sintoma do sistema nervoso, outro" },
  { code: "N70", description: "Poliomielite" },
  { code: "N71", description: "Meningite / encefalite" },
  { code: "N72", description: "Tétano" },
  { code: "N73", description: "Infecção neurológica, outra" },
  { code: "N74", description: "Neoplasia maligna do sistema neurológico" },
  { code: "N75", description: "Neoplasia benigna do sistema neurológico" },
  {
    code: "N76",
    description: "Neoplasia do sistema neurológico de natureza incerta",
  },
  { code: "N79", description: "Concussão" },
  { code: "N80", description: "Lesão craniana, outra" },
  { code: "N81", description: "Lesão do sistema neurológico, outra" },
  { code: "N85", description: "Malformação congénita neurológica" },
  { code: "N86", description: "Esclerose múltipla" },
  { code: "N87", description: "Parkinsonismo" },
  { code: "N88", description: "Epilepsia" },
  { code: "N89", description: "Enxaqueca" },
  { code: "N90", description: "Cefaleia de cluster" },
  { code: "N91", description: "Paralisia facial / paralisia de bell" },
  { code: "N92", description: "Nevralgia do trigémio" },
  { code: "N93", description: "Síndrome do canal cárpico" },
  { code: "N94", description: "Nevrite / neuropatia periférica" },
  { code: "N95", description: "Cefaleia de tensão" },
  { code: "N99", description: "Doença do sistema neurológico, outra" },

  // P - Psychological
  { code: "P01", description: "Sensação de ansiedade / nervosismo / tensão" },
  { code: "P02", description: "Reacção aguda ao stress" },
  { code: "P03", description: "Sensação de depressão" },
  {
    code: "P04",
    description: "Sentir-se / comportar-se de forma irritável / zangada",
  },
  { code: "P05", description: "Sensação / comportamento senil" },
  { code: "P06", description: "Perturbação do sono" },
  { code: "P07", description: "Diminuição do desejo sexual" },
  { code: "P08", description: "Diminuição da satisfação sexual" },
  { code: "P09", description: "Preocupação com a preferência sexual" },
  { code: "P10", description: "Gaguejar, balbuciar, tiques" },
  { code: "P11", description: "Problema de alimentação da criança" },
  { code: "P12", description: "Molhar a cama / enurese" },
  {
    code: "P13",
    description: "Encoprese / outro problema de incontinência fecal",
  },
  { code: "P15", description: "Abuso crónico do álcool" },
  { code: "P16", description: "Abuso agudo do álcool" },
  { code: "P17", description: "Abuso do tabaco" },
  { code: "P18", description: "Abuso de medicação" },
  { code: "P19", description: "Abuso de drogas" },
  { code: "P20", description: "Alteração da memória" },
  { code: "P22", description: "Sinais / sintomas do comportamento da criança" },
  {
    code: "P23",
    description: "Sinais / sintomas do comportamento do adolescente",
  },
  { code: "P24", description: "Dificuldade específica de aprendizagem" },
  { code: "P25", description: "Problema numa fase da vida de um adulto" },
  { code: "P27", description: "Medo de perturbação mental" },
  { code: "P28", description: "Limitação funcional / incapacidade (p)" },
  { code: "P29", description: "Sinal / sintoma psicológico, outro" },
  { code: "P70", description: "Demência" },
  { code: "P71", description: "Psicose orgânica, outra / ne" },
  { code: "P72", description: "Esquizofrenia" },
  { code: "P73", description: "Psicose afectiva" },
  { code: "P74", description: "Distúrbio ansioso / estado de ansiedade" },
  { code: "P75", description: "Somatização" },
  { code: "P76", description: "Perturbação depressiva" },
  { code: "P77", description: "Suicídio / tentativa de suicídio" },
  { code: "P78", description: "Neurastenia / surmenage" },
  { code: "P79", description: "Fobia / perturbação compulsiva" },
  { code: "P80", description: "Alteração da personalidade" },
  { code: "P81", description: "Perturbação hipercinética" },
  { code: "P82", description: "Stress pós-traumático" },
  { code: "P85", description: "Atraso mental" },
  { code: "P86", description: "Anorexia nervosa / bulimia" },
  { code: "P98", description: "Psicose, outra / ne" },
  { code: "P99", description: "Perturbação psicológica, outra" },

  // R - Respiratory
  { code: "R01", description: "Dor atribuída ao aparelho respiratório" },
  { code: "R02", description: "Dificuldade respiratória / dispneia" },
  { code: "R03", description: "Respiração ruidosa" },
  { code: "R04", description: "Problema respiratório, outro" },
  { code: "R05", description: "Tosse" },
  { code: "R06", description: "Hemorragia nasal / epistáxis" },
  { code: "R07", description: "Espirro / congestão nasal" },
  { code: "R08", description: "Sinal / sintoma nasal, outro" },
  { code: "R09", description: "Sinal / sintoma dos seios perinasais" },
  { code: "R21", description: "Sinal / sintoma da garganta" },
  { code: "R23", description: "Sinal / sintoma da voz" },
  { code: "R24", description: "Hemoptise" },
  { code: "R25", description: "Expectoração / mucosidade anormal" },
  { code: "R26", description: "Medo de cancro do aparelho respiratório" },
  { code: "R27", description: "Medo de outra doença respiratória" },
  { code: "R28", description: "Limitação funcional / incapacidade (r)" },
  {
    code: "R29",
    description: "Sinal / sintoma do aparelho respiratório, outro",
  },
  { code: "R71", description: "Tosse convulsa" },
  { code: "R72", description: "Infecção estreptocócica da orofaringe" },
  { code: "R73", description: "Abcesso / furúnculo no nariz" },
  {
    code: "R74",
    description: "Infecção aguda do aparelho respiratório superior",
  },
  { code: "R75", description: "Sinusite crónica / aguda" },
  { code: "R76", description: "Amigdalite aguda" },
  { code: "R77", description: "Laringite / traqueíte aguda" },
  { code: "R78", description: "Bronquite / bronquiolite aguda" },
  { code: "R79", description: "Bronquite crónica" },
  { code: "R80", description: "Gripe" },
  { code: "R81", description: "Pneumonia" },
  { code: "R82", description: "Pleurisia / derrame pleural" },
  { code: "R83", description: "Infecção respiratória, outra" },
  { code: "R84", description: "Neoplasia maligna do brônquio / pulmão" },
  { code: "R85", description: "Neoplasia respiratória maligna, outra" },
  { code: "R86", description: "Neoplasia benigna respiratória" },
  { code: "R87", description: "Corpo estranho no nariz / laringe / brônquios" },
  { code: "R88", description: "Lesão respiratória, outra" },
  {
    code: "R89",
    description: "Malformação congénita do aparelho respiratório",
  },
  { code: "R90", description: "Hipertrofia das amígdalas / adenóides" },
  { code: "R92", description: "Neoplasia respiratória de natureza incerta" },
  { code: "R95", description: "Doença pulmonar obstrutiva crónica" },
  { code: "R96", description: "Asma" },
  { code: "R97", description: "Rinite alérgica" },
  { code: "R98", description: "Sindrome de hiperventilação" },
  { code: "R99", description: "Doença respiratória, outra" },

  // S - Skin
  { code: "S01", description: "Dor / sensibilidade dolorosa da pele" },
  { code: "S02", description: "Prurido" },
  { code: "S03", description: "Verrugas" },
  { code: "S04", description: "Tumor / massa localizada da pele" },
  { code: "S05", description: "Tumores / inchaços generalizados" },
  { code: "S06", description: "Erupção cutânea localizada" },
  { code: "S07", description: "Erupção cutânea generalizada" },
  { code: "S08", description: "Alteração da cor da pele" },
  { code: "S09", description: "Infecção de dedo da mão / pé" },
  { code: "S10", description: "Furúnculo / antraz" },
  { code: "S11", description: "Infecção pós-traumática da pele" },
  { code: "S12", description: "Picada ou mordedura de insecto" },
  { code: "S13", description: "Mordedura animal / humana" },
  { code: "S14", description: "Queimadura / escaldão" },
  { code: "S15", description: "Corpo estranho na pele" },
  { code: "S16", description: "Traumatismo / contusão" },
  { code: "S17", description: "Abrasão / arranhão / bolhas" },
  { code: "S18", description: "Laceração / corte" },
  { code: "S19", description: "Lesão cutânea, outra" },
  { code: "S20", description: "Calos / calosidades" },
  { code: "S21", description: "Sinal / sintoma da textura da pele" },
  { code: "S22", description: "Sinal / sintoma da unha" },
  { code: "S23", description: "Queda de cabelo / calvície" },
  { code: "S24", description: "Sinal / sintoma do cabelo / couro cabeludo" },
  { code: "S26", description: "Medo de cancro da pele" },
  { code: "S27", description: "Medo de outra doença da pele" },
  { code: "S28", description: "Limitação funcional / incapacidade (s)" },
  { code: "S29", description: "Sinal / sintoma da pele, outro" },
  { code: "S70", description: "Herpes zoster" },
  { code: "S71", description: "Herpes simples" },
  { code: "S72", description: "Escabiose / outra acaríase" },
  { code: "S73", description: "Pediculose / outra infestação da pele" },
  { code: "S74", description: "Dermatofitose" },
  { code: "S75", description: "Monilíase / candidíase da pele" },
  { code: "S76", description: "Infecção da pele, outra" },
  { code: "S77", description: "Neoplasia maligna da pele" },
  { code: "S78", description: "Lipoma" },
  { code: "S79", description: "Neoplasia cutânea benigna / incerta" },
  { code: "S80", description: "Queratose solar / queimadura solar" },
  { code: "S81", description: "Hemangioma / linfangioma" },
  { code: "S82", description: "Nevo / sinal da pele" },
  { code: "S83", description: "Lesão congénita da pele" },
  { code: "S84", description: "Impetigo" },
  { code: "S85", description: "Quisto pilonidal / fístula" },
  { code: "S86", description: "Dermatite seborreica" },
  { code: "S87", description: "Dermatite / eczema atópico" },
  { code: "S88", description: "Dermatite de contacto / alérgica" },
  { code: "S89", description: "Eritema das fraldas" },
  { code: "S90", description: "Pitiríase rosada" },
  { code: "S91", description: "Psoríase" },
  { code: "S92", description: "Doença das glândulas sudoríparas" },
  { code: "S93", description: "Quisto sebáceo" },
  { code: "S94", description: "Unha encravada" },
  { code: "S95", description: "Molusco contagioso" },
  { code: "S96", description: "Acne" },
  { code: "S97", description: "Úlcera crónica da pele" },
  { code: "S98", description: "Urticária" },
  { code: "S99", description: "Doença da pele, outra" },

  // T - Endocrine/Metabolic and Nutritional
  { code: "T01", description: "Sede excessiva" },
  { code: "T02", description: "Apetite excessivo" },
  { code: "T03", description: "Perda de apetite" },
  { code: "T04", description: "Problema alimentar do lactente / criança" },
  { code: "T05", description: "Problema alimentar do adulto" },
  { code: "T07", description: "Aumento de peso" },
  { code: "T08", description: "Perda de peso" },
  { code: "T10", description: "Atraso de crescimento" },
  { code: "T11", description: "Desidratação" },
  { code: "T26", description: "Medo de cancro do sistema endócrino" },
  { code: "T27", description: "Medo de outra doença endócrina / metabólica" },
  { code: "T28", description: "Limitação funcional / incapacidade (t)" },
  {
    code: "T29",
    description: "Sinal / sintoma endócrino, metabólico ou nutricional, outros",
  },
  { code: "T70", description: "Infecção endócrina" },
  { code: "T71", description: "Neoplasia maligna da tiróide" },
  { code: "T72", description: "Neoplasia benigna da tiróide" },
  { code: "T73", description: "Neoplasia endócrina, outra / ne" },
  { code: "T78", description: "Quisto do canal tireoglosso" },
  { code: "T80", description: "Malformação endócrina / metabólica congénita" },
  { code: "T81", description: "Bócio" },
  { code: "T82", description: "Obesidade" },
  { code: "T83", description: "Excesso de peso" },
  { code: "T85", description: "Hipertiroidismo / tirotoxicose" },
  { code: "T86", description: "Hipotiroidismo / mixedema" },
  { code: "T87", description: "Hipoglicémia" },
  { code: "T89", description: "Diabetes insulino-dependente" },
  { code: "T90", description: "Diabetes não insulino-dependente" },
  { code: "T91", description: "Deficiência vitamínica / nutricional" },
  { code: "T92", description: "Gota" },
  { code: "T93", description: "Alteração do metabolismo dos lípidos" },
  {
    code: "T99",
    description: "Doença endócrina / metabólica / nutricional, outra",
  },

  // U - Urology
  { code: "U01", description: "Disúria / micção dolorosa" },
  { code: "U02", description: "Micção frequente / urgente" },
  { code: "U04", description: "Incontinência urinária" },
  { code: "U05", description: "Problema com a micção, outro" },
  { code: "U06", description: "Hematúria" },
  { code: "U07", description: "Sinal / sintoma da urina, outro" },
  { code: "U08", description: "Retenção urinária" },
  { code: "U13", description: "Sinal / sintoma da bexiga, outro" },
  { code: "U14", description: "Sinal / sintoma do rim" },
  { code: "U26", description: "Medo de cancro do aparelho urinário" },
  { code: "U27", description: "Medo de outra doença urinária" },
  { code: "U28", description: "Limitação funcional / incapacidade (u)" },
  { code: "U29", description: "Sinal / sintoma do aparelho urinário, outro" },
  { code: "U70", description: "Pielonefrite / pielite" },
  { code: "U71", description: "Cistite / outra infecção urinária" },
  { code: "U72", description: "Uretrite" },
  { code: "U75", description: "Neoplasia maligna do rim" },
  { code: "U76", description: "Neoplasia maligna da bexiga" },
  { code: "U77", description: "Neoplasia maligna do aparelho urinário, outra" },
  { code: "U78", description: "Neoplasia benigna do aparelho urinário" },
  { code: "U79", description: "Neoplasia do aparelho urinário ne" },
  { code: "U80", description: "Lesão traumática do aparelho urinário" },
  { code: "U85", description: "Malformação congénita do aparelho urinário" },
  { code: "U88", description: "Glomerulonefrite / nefrose" },
  { code: "U90", description: "Albuminúria / proteinúria ortostática" },
  { code: "U95", description: "Cálculo urinário" },
  { code: "U98", description: "Análise de urina anormal ne" },
  { code: "U99", description: "Doença urinária, outra" },

  // W - Pregnancy, Childbearing, Family Planning
  { code: "W01", description: "Questão sobre gravidez" },
  { code: "W02", description: "Medo de estar grávida" },
  { code: "W03", description: "Hemorragia antes do parto" },
  { code: "W05", description: "Vómitos / náuseas durante a gravidez" },
  { code: "W10", description: "Contracepção pós-coital" },
  { code: "W11", description: "Contracepção oral" },
  { code: "W12", description: "Contracepção intra-uterina" },
  { code: "W13", description: "Esterilização" },
  { code: "W14", description: "Contracepção, outros" },
  { code: "W15", description: "Infertilidade / subfertilidade" },
  { code: "W17", description: "Hemorragia pós-parto" },
  { code: "W18", description: "Sinal / sintoma do pós-parto, outro" },
  { code: "W19", description: "Sinal / sintoma da mama / lactação" },
  {
    code: "W21",
    description: "Preocupação com a imagem corporal durante a gravidez",
  },
  { code: "W27", description: "Medo de complicação da gravidez" },
  { code: "W28", description: "Limitação funcional / incapacidade (w)" },
  { code: "W29", description: "Sinal / sintoma da gravidez, outro" },
  { code: "W70", description: "Sépsis / infecção puerperal" },
  { code: "W71", description: "Infecção que complica a gravidez" },
  { code: "W72", description: "Neoplasia maligna relacionada com a gravidez" },
  {
    code: "W73",
    description: "Neoplasia benigna / incerta relacionada com a gravidez",
  },
  { code: "W75", description: "Lesão traumática que complica a gravidez" },
  { code: "W76", description: "Malformação congénita que complica a gravidez" },
  { code: "W78", description: "Gravidez" },
  { code: "W79", description: "Gravidez não desejada" },
  { code: "W80", description: "Gravidez ectópica" },
  { code: "W81", description: "Toxémia da gravidez" },
  { code: "W82", description: "Aborto espontâneo" },
  { code: "W83", description: "Aborto provocado" },
  { code: "W84", description: "Gravidez de alto risco" },
  { code: "W85", description: "Diabetes gestational" },
  { code: "W90", description: "Parto sem complicações de nado vivo" },
  { code: "W91", description: "Parto sem complicações de nado morto" },
  { code: "W92", description: "Parto com complicações de nado vivo" },
  { code: "W93", description: "Parto com complicações de nado morto" },
  { code: "W94", description: "Mastite puerperal" },
  {
    code: "W95",
    description: "Problema da mama durante a gravidez / puerpério, outro",
  },
  { code: "W96", description: "Complicação do puerpério, outra" },
  { code: "W99", description: "Problema da gravidez / parto, outro" },

  // X - Female Genital System (including Breast)
  { code: "X01", description: "Dor genital" },
  { code: "X02", description: "Dor menstrual" },
  { code: "X03", description: "Dor intermenstrual" },
  { code: "X04", description: "Relação sexual dolorosa na mulher" },
  { code: "X05", description: "Menstruação escassa / ausente" },
  { code: "X06", description: "Menstruação excessiva" },
  { code: "X07", description: "Menstruação irregular / frequente" },
  { code: "X08", description: "Hemorragia inter-menstrual" },
  { code: "X09", description: "Sinal / sintoma pré-menstrual" },
  { code: "X10", description: "Desejo de alterar a data da menstruação" },
  { code: "X11", description: "Sinal / sintoma da menopausa" },
  { code: "X12", description: "Hemorragia pós-menopausa" },
  { code: "X13", description: "Hemorragia pós-coito" },
  { code: "X14", description: "Secreção vaginal" },
  { code: "X15", description: "Sinal / sintoma da vagina, outro" },
  { code: "X16", description: "Sinal / sintoma da vulva" },
  { code: "X17", description: "Sinal / sintoma da pélvis feminina" },
  { code: "X18", description: "Dor na mama feminina" },
  { code: "X19", description: "Tumor / nódulo da mama feminina" },
  { code: "X20", description: "Sinal / sintoma do mamilo na mulher" },
  { code: "X21", description: "Sinal / sintoma da mama feminina, outro" },
  { code: "X22", description: "Preocupação com a aparência da mama feminina" },
  {
    code: "X23",
    description: "Medo de doença sexualmente transmissível na mulher",
  },
  { code: "X24", description: "Medo de disfunção sexual na mulher" },
  { code: "X25", description: "Medo de cancro genital na mulher" },
  { code: "X26", description: "Medo de cancro da mama na mulher" },
  {
    code: "X27",
    description: "Medo de outra doença genital / da mama na mulher",
  },
  { code: "X28", description: "Limitação funcional / incapacidade (x)" },
  {
    code: "X29",
    description: "Sinal / sintoma do aparelho genital feminino, outro",
  },
  { code: "X70", description: "Sífilis feminina" },
  { code: "X71", description: "Gonorreia feminina" },
  { code: "X72", description: "Candidíase genital na mulher" },
  { code: "X73", description: "Tricomoníase genital na mulher" },
  { code: "X74", description: "Doença inflamatória pélvica" },
  { code: "X75", description: "Neoplasia maligna do colo" },
  { code: "X76", description: "Neoplasia maligna da mama feminina" },
  { code: "X77", description: "Neoplasia maligna genital feminina, outra" },
  { code: "X78", description: "Fibromioma do útero" },
  { code: "X79", description: "Neoplasia benigna da mama feminina" },
  { code: "X80", description: "Neoplasia benigna genital feminina" },
  {
    code: "X81",
    description: "Neoplasia genital feminina de natureza incerta / outra",
  },
  { code: "X82", description: "Lesão traumática genital feminino" },
  { code: "X83", description: "Malformação congénita genital" },
  { code: "X84", description: "Vaginite / vulvite ne" },
  { code: "X85", description: "Doença do colo ne" },
  { code: "X86", description: "Esfregaço de papanicolau anormal" },
  { code: "X87", description: "Prolapso útero-vaginal" },
  { code: "X88", description: "Doença fibroquística da mama" },
  { code: "X89", description: "Síndrome de tensão pré-menstrual" },
  { code: "X90", description: "Herpes genital feminino" },
  { code: "X91", description: "Condiloma acuminado feminino" },
  { code: "X92", description: "Infecção genital por chlamydia" },
  { code: "X99", description: "Doença genital feminino, outra" },

  // Y - Male Genital System
  { code: "Y01", description: "Dor no pénis" },
  { code: "Y02", description: "Dor no escroto / testículos" },
  { code: "Y03", description: "Secreção uretral" },
  { code: "Y04", description: "Sinal / sintoma do pénis, outro" },
  {
    code: "Y05",
    description: "Sinal / sintoma do escroto / testículos, outro",
  },
  { code: "Y06", description: "Sinal / sintoma da próstata" },
  { code: "Y07", description: "Impotência ne" },
  { code: "Y08", description: "Sinal / sintoma da função sexual masculina" },
  { code: "Y10", description: "Infertilidade / subfertilidade masculina" },
  { code: "Y13", description: "Esterilização masculina" },
  { code: "Y14", description: "Planeamento familiar no homem, outro" },
  { code: "Y16", description: "Sinal / sintoma da mama masculina" },
  { code: "Y24", description: "Medo de disfunção sexual no homem" },
  {
    code: "Y25",
    description: "Medo de doença sexualmente transmissível no homem",
  },
  { code: "Y26", description: "Medo de cancro genital masculino" },
  { code: "Y27", description: "Medo de outra doença genital masculina" },
  { code: "Y28", description: "Limitação funcional / incapacidade (y)" },
  { code: "Y29", description: "Sinal / sintoma genital masculino, outro" },
  { code: "Y70", description: "Sífilis masculina" },
  { code: "Y71", description: "Gonorreia masculina" },
  { code: "Y72", description: "Herpes genital no homem" },
  { code: "Y73", description: "Prostatite / vesiculite seminal" },
  { code: "Y74", description: "Orquite / epididimite" },
  { code: "Y75", description: "Balanite" },
  { code: "Y76", description: "Condiloma acuminado" },
  { code: "Y77", description: "Neoplasia maligna da próstata" },
  { code: "Y78", description: "Neoplasia maligna genital maculino, outra" },
  { code: "Y79", description: "Neoplasia benigna / incerta genital masculino" },
  { code: "Y80", description: "Traumatismo genital masculino, outro" },
  { code: "Y81", description: "Fimose / prepúcio redundante" },
  { code: "Y82", description: "Hipospádias" },
  { code: "Y83", description: "Testículo não descido" },
  { code: "Y84", description: "Malformação congénita genital no homem, outra" },
  { code: "Y85", description: "Hipertrofia prostática benigna" },
  { code: "Y86", description: "Hidrocelo" },
  { code: "Y99", description: "Doença genital masculino, outra" },

  // Z - Social Problems
  { code: "Z01", description: "Pobreza / problema económico" },
  { code: "Z02", description: "Problema relacionado com a água / alimentação" },
  { code: "Z03", description: "Problema de habitação / vizinhança" },
  { code: "Z04", description: "Problema socio-cultural" },
  { code: "Z05", description: "Problema com as condições de trabalho" },
  { code: "Z06", description: "Problema de desemprego" },
  { code: "Z07", description: "Problema relacionado com a educação" },
  {
    code: "Z08",
    description: "Problema relacionado com o sistema de segurança social",
  },
  { code: "Z09", description: "Problema legal" },
  { code: "Z10", description: "Problema relacionado com o sistema de saúde" },
  { code: "Z11", description: "Problema com o estar doente" },
  { code: "Z12", description: "Problema relacional com o parceiro" },
  { code: "Z13", description: "Problema comportamental do parceiro" },
  { code: "Z14", description: "Problema por doença do parceiro" },
  { code: "Z15", description: "Perda ou falecimento do parceiro" },
  { code: "Z16", description: "Problema relacional com uma criança" },
  { code: "Z18", description: "Problema com uma criança doente" },
  { code: "Z19", description: "Perda ou falecimento de uma criança" },
  { code: "Z20", description: "Problema relacional com familiares" },
  { code: "Z21", description: "Problema comportamental de familiar" },
  { code: "Z22", description: "Problema por doença de familiar" },
  { code: "Z23", description: "Perda / falecimento de familiar" },
  { code: "Z24", description: "Problema relacional com amigos" },
  { code: "Z25", description: "Acto / acontecimento violento" },
  { code: "Z27", description: "Medo de problema social" },
  { code: "Z28", description: "Limitação funcional / incapacidade (z)" },
  { code: "Z29", description: "Problema social ne" },
];
